### ISSUE TITLE
Qalesiz

### ISSUE THREAD

**Issue by noonosh** [mirsaid-mirzohidov/mirsaid-mirzohidov#1]
Nima gap Mirsaid? Saytda form toldirgan ekansiz, manga keldi. Lekin sizga qattan qaytib chiqishni topolmadim. Shu yerda issue ochib qoyaverdim) Qandaysiz? Ishlaringiz qalay?

**Comment by jakhongirn** [comment]
Buyam bir commit-da))

**Comment by noonosh** [comment]
@jaykhans haa bolaaa, man kormabmanku bu yozganini ;)
